### ISSUE TITLE
Fishflux installation issue

### ISSUE THREAD

**Issue by statts8** [nschiett/fishflux#12]
Upon installation attempt it's throwing an error:

Error: object ‘species_list’ is not exported by 'namespace:rfishbase'
Execution halted

I've tried on the latest version R (4.4.1) and an older one (4.2.2) and get the same result.

<img width="590" alt="fishflux issue" src="https://github.com/user-attachments/assets/e21bc173-84a3-4481-9362-1de9cdd39ea1">

**Comment by statts8** [comment]
I deleted import species_list from the NAMESPACE file and the package now downloads

**Comment by dbarneche** [comment]
Hi @statts8 apologies for the delayed reply, we're currently working on a solution.

**Comment by nschiett** [comment]
Thanks for raising the issue. 
Thanks to @dbarneche, the package is now updated and you should be able to install it from GitHub again.
